:input:
  :read_file:
    :path_csv_file: '/Users/mcberros/workspace/translate_german_words/'
    :file_name: 'GermanWords.csv'
    :dictionary_hostname: 'http://en.pons.eu/dict/search/results/'
  :search_in_dictionary:
    :browser: :firefox
    :selenium_webdriver_path: '/Applications/Firefox.app/Contents/MacOS/firefox'

:output:
  :path_csv_file: '/Users/mcberros/workspace/translate_german_words/'
  :file_name: 'GermanWordsTranslation'
  :sufix_file: '.csv'

